### ISSUE TITLE
How to use this plugin in ionic 2

### ISSUE THREAD

**Issue by blueror815** [sarriaroman/FabricPlugin#104]
I am going to use this plugin in ionic 2.
but i could not find any way to use it.
Could you please help me to use it?

**Comment by sarriaroman** [comment]
Hi, just install it using cordova add https://github.com/sarriaroman/FabricPlugin

Add the typings to your d.ts file and look for the API in window.fabric. That is all

**Comment by aashishvyas** [comment]
I have install this plugin in my ionic 3 project but not able to access fabric variable on window.

window.fabric.Crashlytics.sendCrash();
here fabric is not accessible

**Comment by lumitor2** [comment]
@aashishvyas Have you tried this again after build on device? Fabric plugin was unavailable in browser for me.

**Comment by sarriaroman** [comment]
This is a native plugin that requires native bindings, you won't be able to use it on the browser. I recommend you to check if you are in native or in the browser to make the calls.

**Comment by aashishvyas** [comment]
@lumitor2 @sarriaroman  m not able to run the project as fabric is not resolved & getting error at compile time only
![fabric](https://user-images.githubusercontent.com/30458147/29172062-54ca6162-7dfc-11e7-8e57-24029e35cd3c.png)

**Comment by lumitor2** [comment]
@sarriaroman try to use (<any>window).fabric.Crashlytics for TypeScript

**Comment by sarriaroman** [comment]
Did you include the typings file in your project typings file? If you are using window scope, did you define fabric into it?

**Comment by aashishvyas** [comment]
@lumitor2  tried but not working.

**Comment by aashishvyas** [comment]
@sarriaroman  yes i have included the typings file in project

**Comment by davidquon** [comment]
I have a log service that does something like this which is working for me with Ionic 2.2.1.

```
@Injectable()
export class LogService {
  private handler: any;

  constructor(public platform: Platform) {
    platform.ready().then(
      () => this.setup()
    )
  }

  private setup() {
    if (!window['fabric']) return;

    this.handler = window['fabric'];
  }

  // NOTE: For testing ONLY!!!
  public sendCrash() {
    if (!this.handler) {
      console.warn('Fabric not available: sendCrash');
      return;
    }

    this.handler.Crashlytics.sendCrash();
  }
}
```

**Comment by blueror815** [comment]
hello @sarriaroman,
I am not sure about your word,
" ```Add the typings to your d.ts file and look for the API in window.fabric.```"
could you please explain about the way in more details?

**Comment by blueror815** [comment]
hello @aashishvyas 
how can i add typings to d.ts?
and where can i find d.ts?

**Comment by blueror815** [comment]
hello @sarriaroman 
Can you help me to install this plugin in ionic 3?
I am still waiting for your reply.

**Comment by lumitor2** [comment]
@blueror815 have you tried to put this in your tsconfig.json file?
`
  "files": [
      "plugins/cordova-fabric-plugin/typings/cordova-fabric-plugin.d.ts"
    ]
`

**Comment by aashishvyas** [comment]
@lumitor2  after adding the above lines to tsconfig.json file m able to access fabric variable & able to call all methods bit at run time m getting error as 
Uncaught (in promise): ReferenceError: fabric is not defined ReferenceError: fabric is not defined at new HomePage

**Comment by lumitor2** [comment]
@aashishvyas Fabric library (in fabric variable) is available after you build your app to real device / simulator. You can try (window).fabric.Crashlytics.sendCrash(); to invoke app crash and see records in Fabric dashboard.

**Comment by blueror815** [comment]
@lumitor2 
I did not try.
so after installation of this plugin, should i add the above line to `tsconfig.json`?
and after adding the above line, can i access it with `(window).fabric.` in any place without any importaing?

**Comment by lumitor2** [comment]
@blueror815 Yes. You can access it on device only. So there is no global fabric variable accessible in ionic serve (in browser view).
You can even add it before actual Ionic Error handler -> https://github.com/sarriaroman/FabricPlugin/issues/61#issuecomment-306403667

**Comment by blueror815** [comment]
@lumitor2 , thanks.
let me try

**Comment by blueror815** [comment]
hello @lumitor2 
Do i need to install this plugin according to each platform?
To install this plugin, i need to get API_KEY and Secret_key
How can i get those?
I know Fabric.io provides each iOS and Android key.
So i want to know how can i those keys for ionic.
Please let me know

**Comment by aashishvyas** [comment]
@lumitor2 thanx m able to  invoke app crash and see records in Fabric dashboard.

**Comment by lumitor2** [comment]
@aashishvyas nice to hear that! :)
@blueror815 For Ionic app there is only one installation and no need to do anything more for each platform. Your API_KEY and API_SECRED can be found after login to Fabric on https://fabric.io/kits/ios/crashlytics/install in part Add a Run Script Build Phase. Under the picture there is command in this format:
`"${PODS_ROOT}/Fabric/run" API_KEY API_SECRET`

**Comment by aashishvyas** [comment]
@lumitor2 one issue i m facing that this plugin is not able to register crashes which produced in ts code.Only if m invoke its sendCrash method den only crash registered at portal.

**Comment by lumitor2** [comment]
@aashishvyas you can make your own ErrorHandler which extends IonicErrorHandler:
https://github.com/sarriaroman/FabricPlugin/issues/61#issuecomment-306403667

**Comment by lumitor2** [comment]
@aashishvyas I hope, that crash will appear in Fabric dashboard because of triggers in native code. You cand send only non-fatal errors. So you have to filter these in dashboard.

**Comment by aashishvyas** [comment]
@lumitor2 and where i need to provide that class?

**Comment by lumitor2** [comment]
You can make folder in src/ (for example handlers).. Afterwards add it to app.module.ts to this line:
`  providers: [
    { provide: ErrorHandler, useClass: YOURErrorHandler },`

**Comment by aashishvyas** [comment]
but in above link which u mention given that we need to create custom error handler in app.module.ts

**Comment by lumitor2** [comment]
There is no difference, if you put it in folder od directly to app.module.ts.

**Comment by aashishvyas** [comment]
if i put this in app.module.ts den m getting error at compile time  Class 'MyErrorHandler' used before its declaration

**Comment by lumitor2** [comment]
-> create folder for it
-> add code to file (with extends IonicErrorHandler part - https://github.com/sarriaroman/FabricPlugin/issues/61#issuecomment-306403667)
-> change class in useClass to your error handler file name in app.module.ts (don't forget to import your error handler)

**Comment by aashishvyas** [comment]
done whatever u said but still non-fatal errors are not registered at portal

**Comment by Jacotb** [comment]
The plugin doesn't seem to be working so well. 

What works:

- Logging native crashes on iOS
- Logging native crashes on Android 
- Logging non-fatal (js) errors on iOS using `Crashlytics.recordError()`. However this does not include stack traces. Workaround: serialize the stack trace in the error message.

What doesn't work:

- Logging non-fatal crashes on Androind
- Stack traces for non-fatal crashes on iOS

I've tried [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase) as alternative, but the support seems even worse.

**Comment by Dinesh-Jadhav** [comment]
@aashishvyas  Its still not working when  I have included "files": [ "plugins/cordova-fabric-plugin/typings/cordova-fabric-plugin.d.ts" ]
in tsconfig.json file 
In home page console.log(window.fabric) is undefined

**Comment by amamitpandey** [comment]
Simply use like this it is working in ionic 3
window['fabric'].Crashlytics.addLog("about to send a crash for testing!");

**Comment by uniphonic** [comment]
> The plugin doesn't seem to be working so well.
> 
> What works:
> 
> * Logging native crashes on iOS
> * Logging native crashes on Android
> * Logging non-fatal (js) errors on iOS using `Crashlytics.recordError()`. However this does not include stack traces. Workaround: serialize the stack trace in the error message.
> 
> What doesn't work:
> 
> * Logging non-fatal crashes on Android using `Crashlytics.sendNonFatalCrash()`
> * Stack traces for non-fatal crashes on iOS
> 
> I've tried [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase) as alternative, but the support seems even worse.

I had a similar issue, but fixed it by making sure to pass all parameters for the sendNonFatalCrash method. It turns out the second parameter is not optional.

**Comment by chethangowda** [comment]
@lumitor2 i am not able to install fabric plugin for ionic 3 application getting below error can you help me here

> Failed to fetch plugin git+https://github.com/sarriaroman/FabricPlugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CKG\AppData\Roaming\npm-cache\_logs\2018-12-12T12_30_14_910Z-debug.log
[ERROR] An error occurred while running cordova plugin add cordova-fabric-plugin --variable
        FABRIC_API_KEY=4851c0fcd0c20... (exit code 1).
